# HW 2

In [1]:
# Make a path to the file

import os

water_file = os.path.join('data', 'water.xyz')

In [2]:
# Read in the file

import numpy

water = numpy.genfromtxt(fname=water_file, skip_header=2, dtype='unicode')

print(water)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [3]:
# Slice just the data, recast as float

data = water[:, 1:]

data = data.astype(numpy.float)

print(data)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [4]:
# Slice just the atom names

atom_names = water[:,0]

print(atom_names)

['O' 'H1' 'H2']


In [5]:
# Slice just the X positions, Y positions, Z positions

x = data[:,0]

y = data[:,1]

z = data[:,2]

print(x)
print(y)
print(z)

[ 0. -0.  0.]
[-0.007156  0.001486  0.931026]
[ 0.965491 -0.003471  1.207929]


In [6]:
# Calculate the distances between each pair of atoms

for atom1 in range(0, len(atom_names)):
    
    for atom2 in range(0, len(atom_names)):
        
        distance = numpy.sqrt(((x[atom1]-x[atom2])**2 + (y[atom1]-y[atom2])**2 + (z[atom1]-z[atom2])**2))
        
        print(F'{atom_names[atom1]} to {atom_names[atom2]} = {distance}')

O to O = 0.0
O to H1 = 0.9690005374652793
O to H2 = 0.9690003348647513
H1 to O = 0.9690005374652793
H1 to H1 = 0.0
H1 to H2 = 1.52693633514957
H2 to O = 0.9690003348647513
H2 to H1 = 1.52693633514957
H2 to H2 = 0.0


In [24]:
# Calculate the distances, but eliminate zeroes

print(F'The non-zero atomic distances are:')

for atom1 in range(0, len(atom_names)):
    
    for atom2 in range(0, len(atom_names)):
        
        if atom1 != atom2: # This will eliminate self-self (zero) distances
        
            distance = numpy.sqrt(((x[atom1]-x[atom2])**2 + (y[atom1]-y[atom2])**2 + (z[atom1]-z[atom2])**2))
        
            print(F'{atom_names[atom1]} to {atom_names[atom2]} = {distance}')

The non-zero atomic distances are:
O to H1 = 0.9690005374652793
O to H2 = 0.9690003348647513
H1 to O = 0.9690005374652793
H1 to H2 = 1.52693633514957
H2 to O = 0.9690003348647513
H2 to H1 = 1.52693633514957


In [25]:
# Calculate the distances, but eliminate zeroes and duplicates

print(F'The atomic distances are:')

for atom1 in range(0, len(atom_names)):
    
    for atom2 in range(0, len(atom_names)):
        
        if atom1 < atom2: # This will eliminate self-self (zero) distances AND duplicates
        
                distance = numpy.sqrt(((x[atom1]-x[atom2])**2 + (y[atom1]-y[atom2])**2 + (z[atom1]-z[atom2])**2))
        
                print(F'{atom_names[atom1]} to {atom_names[atom2]} = {distance}')

The atomic distances are:
O to H1 = 0.9690005374652793
O to H2 = 0.9690003348647513
H1 to H2 = 1.52693633514957


In [57]:
# Calculate the distances, but eliminate zeroes and duplicates, and set a criteria for bond cutoff

for atom1 in range(0, len(atom_names)):
    
    for atom2 in range(0, len(atom_names)):
        
        if atom1 < atom2: # This will eliminate self-self (zero) distances AND duplicates
        
                distance = numpy.sqrt(((x[atom1]-x[atom2])**2 + (y[atom1]-y[atom2])**2 + (z[atom1]-z[atom2])**2))
            
                # Set a criteron for O-H bonds
                if atom_names[atom1]=='O' and (atom_names[atom2]=='H1' or atom_names[atom2]=='H2') and distance < 0.97:
                    
                    print(F'Bond: {atom_names[atom1]} to {atom_names[atom2]} = {distance}')
                    
                elif atom_names[atom1]=='O' and (atom_names[atom2]=='H1' or atom_names[atom2]=='H2') and distance > 0.97:
                    
                    print(F'Not a bond: {atom_names[atom1]} to {atom_names[atom2]} = {distance}')
                
                # Set a criteron for H-H bonds
                if atom_names[atom1]=='H1' and atom_names[atom2]=='H2' and distance < 0.66:
                    
                    print(F'Bond: {atom_names[atom1]} to {atom_names[atom2]} = {distance}')
                    
                elif atom_names[atom1]=='H1' and atom_names[atom2]=='H2' and distance > 0.66:
                    
                    print(F'Not a bond: {atom_names[atom1]} to {atom_names[atom2]} = {distance}')

Bond: O to H1 = 0.9690005374652793
Bond: O to H2 = 0.9690003348647513
Not a bond: H1 to H2 = 1.52693633514957
