# HW2 (geometry analysis) homework solution

In [1]:
import numpy
import os

In [2]:
file_location = os.path.join('data','water.xyz')
print(file_location)

data/water.xyz


In [4]:
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')

In [5]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [6]:
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(numpy.float)

In [7]:
print(symbols)

['O' 'H1' 'H2']


In [8]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


$$ distance = [(x_1 - x_2)^2 + (y_1 - y_2)^2 + (z_1 - z_2)]^\frac{1}{2}) $$

In [11]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        atom_distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]}: {atom_distance:.3f}') # .3f means print just 3 decimal places

O to O: 0.000
O to H1: 0.969
O to H2: 0.969
H1 to O: 0.969
H1 to H1: 0.000
H1 to H2: 1.527
H2 to O: 0.969
H2 to H1: 1.527
H2 to H2: 0.000


In [12]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        atom_distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        
        if atom_distance <= 1.5:
            print(F'{symbols[num1]} to {symbols[num2]}: {atom_distance:.3f}') # .3f means print just 3 decimal places

O to O: 0.000
O to H1: 0.969
O to H2: 0.969
H1 to O: 0.969
H1 to H1: 0.000
H2 to O: 0.969
H2 to H2: 0.000


In [14]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        atom_distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        
        if atom_distance > 0 and atom_distance <= 1.5:
            print(F'{symbols[num1]} to {symbols[num2]}: {atom_distance:.3f}') # .3f means print just 3 decimal places

O to H1: 0.969
O to H2: 0.969
H1 to O: 0.969
H2 to O: 0.969


In [15]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        
        if num1<num2:
        
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            atom_distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)

            if atom_distance > 0 and atom_distance <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]}: {atom_distance:.3f}') # .3f means print just 3 decimal places

O to H1: 0.969
O to H2: 0.969


In [17]:
# COLLECT IT ALL IN ONE BOX

import numpy
import os

file_location = os.path.join('data','water.xyz')

xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')

symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(numpy.float)

num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        
        if num1<num2:
        
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            atom_distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)

            if atom_distance > 0 and atom_distance <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]}: {atom_distance:.3f}') # .3f means print just 3 decimal places

O to H1: 0.969
O to H2: 0.969
